### ISSUE TITLE
Staging sequencer provides outdated information on registered identities

### ISSUE THREAD

**Issue by paolodamico** [worldcoin/signup-sequencer#143]
**Version**

Latest `main` version. 

**Platform**
UNIX. Deployed version of staging sequencer.

**Description**

Once an identity has been added to the sequencer, the `/inclusionProof` endpoint will always return a valid Merkle root and proof. However, we recently implemented changes in which identities are only valid for ~1 hour. If will keep this measure around, we have to make sure the `/inclusionProof` returns a proper response that indicates the identity is stale/unverified.

This could introduce noise for people on the HackMoney hackathon, so we should aim to fix soon. CC @philsippl @recmo

**Comment by philsippl** [comment]
#180 returns an error `Root mismatch between tree and contract.` now in that case.
