### ISSUE TITLE
Split log fetch into smaller block range when the request fails due to timeout.

### ISSUE THREAD

**Issue by recmo** [worldcoin/signup-sequencer#240]
https://docs.alchemy.com/reference/eth-getlogs

The Alchemy `eth_getlogs` call can fail if the request is too large to process. But using too small requests is costly. We have been adjusting the block range size regularly, but depending on Alchemy / Polygon load this arbitrarily fails.

We should dynamically adjust the range. If the request fails with an error indicating it is too large we should retry with a smaller range (say a quarter).

**Comment by gswirski** [comment]
This was implemented in https://github.com/worldcoin/signup-sequencer/pull/283
