### ISSUE TITLE
Cache the merkle tree.

### ISSUE THREAD

**Issue by recmo** [worldcoin/signup-sequencer#243]
On start the sequencer syncs the tree from scratch. This takes a minute and involves many `log_fetch` queries. We should

* Cache the tree in persistent storage.
* Check tree consistency on load.
* Check tree root against chain on start.
* Sync only new leafs.
* Check state root and if invalid either
   * Wipe the state and resync, or
   * Crash.

**Comment by recmo** [comment]
Instead of caching the entire tree we should just cache the log events. Caching closer to raw input reduces the chances of cache corruption. Plus the processing has neglible overhead anyway.

**Comment by gswirski** [comment]
@recmo Caching is implemented now. I'm closing the ticket.
