### ISSUE TITLE
Work queue for `insert_identity`

### ISSUE THREAD

**Issue by recmo** [worldcoin/signup-sequencer#258]
Right now the `insert_identity` API call is fully synchronous:

1. It receives an HTTP POST on `/insertIdentity`.
2. It parses and validates the request.
3. It takes the global tree lock (exclusive write).
4. It checks for duplicate insertions.
5. It creates and signs an Ethereum transaction.
6. It waits for the transaction to be mined.
7. It updates the internal tree representation.
8. It downgrades the lock to a non-exclusive read lock.
9. It verifies the tree-root against the on-chain one.
10. It releases the global tree lock.
11. It returns a response to the API request.

The exclusive global lock prevents concurrent request handling and steps 5-6 can take a lot of time and/or fail. 

---

Instead we want to get rid of the lock, create a work-queue and split this up in three separate threads, A, B, C:

A:
1. A receives an HTTP POST on `/insertIdentity`.
2. A parses and validates the request.
4. A checks for duplicate insertions. (TBD: How?)
5. A inserts the identity in the work-queue.
6. A returns a response to the request.

B:
1. It takes an item from the work-queue.
2. It flags it as in-progress.
2. It creates and signs an Ethereum transaction.
3. It waits for the transaction to be mined.
4. Marks the work item as done.

C:
1. Monitors the events.
2. Updates the internal tree on new events.
3. Checks the tree-root for consistency.
4. TBS: Check the events against the work-queue for consistency?

**Comment by gswirski** [comment]
Done in #284
