### ISSUE TITLE
Block confirmation minimum for transaction settlement.

### ISSUE THREAD

**Issue by recmo** [worldcoin/signup-sequencer#271]
Currently we only wait for the transaction to be mined, not for any confirmations. We should wait a configurable number of blocks before considering the transaction 'done'.

https://github.com/worldcoin/signup-sequencer/blob/f0971fbe84aedfe16509bb2047d236c58788ebe2/src/ethereum/mod.rs#L432

**Comment by gswirski** [comment]
This is implemented in: https://github.com/worldcoin/signup-sequencer/pull/284
