### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by recmo** [worldcoin/signup-sequencer#309]
Right now a startup *with* cached events takes 5 min. Ideally we make this less than ten seconds so sporadic crashes do not hurt the uptime much. We should profile this to be sure, but likely causes are:

1. The O(n) duplicate search for each inserted leaf.
2. Computing the merkle root for each update.
3. Logging an event for each leaf

No. 1. can be addresses by

1. skipping the check (we only log it, we don't act on it when processing events),
2. using a hash table or other more efficient duplicate check,
3. doing an efficient duplicate check at the end over all leaves, for example by sorting.

No 2 can be addressed by not recomputing the merkle tree nodes for each leaf update. For example we could do all insertions, then recompute all intermediate nodes and verify the final root. Downside is that corruption can no longer be addressed to a specific leaf, so maybe we should keep the per-leaf functionality around under a flag for debugging purposes.

No 3 is just plain annoying and should be removed.

A more elaborate mid/long term solution is to keep the tree in database instead of in memory so it persist between runs.

**Comment by gswirski** [comment]
With the suggested changes (all checks except for the final root validation removed, single merkle tree recompute, limited logging), it still starts up in around 30 seconds on my local Apple M2 machine.

The main problem then becomes our cache schema. Loading 500k JSONs and then parsing them takes 20 seconds, even locally. If we instead load only leaf and root hashes, it becomes negligible.

**Comment by gswirski** [comment]
With https://github.com/worldcoin/signup-sequencer/pull/339 deployed, our startup time is around 15s.
